#!/bin/bash
set -euo pipefail
psql --quiet --no-align --tuples-only --set ON_ERROR_STOP= <<<"
    select jsonb_build_object(
        'type', 'FeatureCollection',
        'features', jsonb_agg(
            jsonb_build_object(
                'type', 'Feature',
                'geometry', st_asgeojson(tract.point)::jsonb,
                'properties', jsonb_build_object(
                    'ageCategory', age_category,
                    'siteCategory', site_category
                )
            )
        )
    )

    from shipping.metadata_for_augur_build_v3
    join warehouse.tract on (tract.identifier = residence_census_tract)

    where date >= '2019-10-01'
      and age_category in ('child', 'adult')
      and site_category in ('clinic', 'community', 'hospital')
"
