#!/bin/bash
set -euo pipefail

# Metabase image version
version="v0.32.8"
network="metabase-bridge"

main() {
    # Create a user-defined bridge network for the container to use instead of
    # the default bridge network.
    if docker network inspect "$network" >/dev/null 2>&1; then
        log "Using existing Docker network $network"
    else
        log "Creating Docker network $network"
        docker network create "$network"
    fi

    log "Creating container metabase ($version)"
    docker container create \
        --name metabase \
        --env MB_DB_TYPE=postgres \
        --env MB_DB_HOST=production.db.seattleflu.org \
        --env MB_DB_PORT=5432 \
        --env MB_DB_DBNAME=metabase \
        --env MB_DB_USER=metabase \
        --env MB_DB_PASS \
        --env JAVA_TIMEZONE=US/Pacific \
        --network "$network" \
        --publish 127.0.0.1:3000:3000 \
        metabase/metabase:"$version"
}

log() {
    echo "->" "$@" >&2
}

main "$@"
