#!/bin/bash
# usage: ./dev/add-user-to-all-projects

# Required environment variables:
#   - REDCAP_API_URL
#   - SRC_USER: The UW NetID of the user whose permissions you are copying for
#       all REDCap projects. See ./dev/export-redcap-user.
#   - DST_USER: The UW NetID of the destination user whose permissions you are
#       importing for all REDCap projects. See ./dev/import-redcap-user.
#   - Many, many REDCap API tokens
#
set -euo pipefail

: "${REDCAP_API_URL:?The REDCAP_API_URL environment variable is required.}"
: "${SRC_USER:?The SRC_USER environment variable is required.}"
: "${DST_USER:?The DST_USER environment variable is required.}"


for pid in \
    16637 \
    16691 \
    16949 \
    17421 \
    17542 \
    19209 \
    19212 \
    19338 \
    20190 \
    20759 \
    21512 \
    21514 \
    21520 \
    21521 \
    21808 \
    21809 \
    21810 \
    21950 \
    21951 \
    21953 \
    22461 \
    22467 \
    22468 \
    22469 \
    22470 \
    22471 \
    22472 \
    22473 \
    22474 \
    22475 \
    22476 \
    22477 \
    23089 ;
do
    if ! ./dev/import-redcap-user \
        --permissions <(./dev/export-redcap-user --project-id "$pid" --net-id "$SRC_USER") \
        --project-id "$pid" --net-id "$DST_USER"
    then
        echo "Failed to import user for PID $pid" >&2
        echo >&2
    fi

done;
