#!/usr/bin/env python3
# usage: ./dev/export-redcap-user --net-id <net-id> --project-id <project-id>
#
# Exports the given REDCap user's metadata and permissions from the project
# specified by the REDCap API token environment variable.
# Useful for deriving permissions configurations for ./dev/import-redcap-user.
# The returned user's information is printed to stdout, so you'll likely want to
# redirect to a new file.
#
# Raises an Exception if the given user does not exist in the REDCap project.
#
# See the REDCap Export Users API v10.1.4 Documentation for more info.
#
# Required environment variables:
#   - REDCAP_API_TOKEN
#   - REDCAP_API_URL
#
import os
import json
import argparse
import id3c.cli.redcap as redcap


parser = argparse.ArgumentParser(
    description= __doc__,
    formatter_class=argparse.RawTextHelpFormatter
)

parser.add_argument("--project-id",
    required=True,
    metavar="<project-id>",
    help="A REDCap project ID")

parser.add_argument("--net-id",
    required=True,
    metavar="<net-id>",
    help="A user's UW NetID")

args = parser.parse_args()

project = redcap.Project(os.environ['REDCAP_API_URL'], args.project_id)
users = project.users()

# We only want permissions for the user with the given UW NetID
try:
    user = next(u for u in users if u["username"] == f"{args.net_id}@washington.edu")
except StopIteration as e:
    raise Exception(f"No user found in the given REDCap project with --net-id {args.net_id}")

print(json.dumps(user))
