#!/usr/bin/env python3
# usage: ./dev/import-redcap-user --permissions <permissions> --net-id <net-id> --project-id <project-id>
#
# Imports a REDCap user to the project specified by the REDCap API token
# environment variable, granting them the given permissions.
#
# Prints the number of users with permissions added or updated to stdout.
#
# See the REDCap Import Users API v10.1.4 Documentation for more info.
#
# Required environment variables:
#   - REDCAP_API_TOKEN
#   - REDCAP_API_URL
#
import os
import sys
import json
import argparse
import id3c.cli.redcap as redcap


parser = argparse.ArgumentParser(
    description= __doc__,
    formatter_class=argparse.RawTextHelpFormatter
)

parser.add_argument("--project-id",
    required=True,
    help="A REDCap project ID")
parser.add_argument("--permissions",
    required=True,
    default=sys.stdin,
    help="A JSON object of permissions to grant a user in this REDCap project. "
    "Can be a different user's exported permissions. Defaults to reading from "
    "stdin.")
parser.add_argument("--net-id",
    required=True,
    metavar="<net-id>",
    help="A user's UW NetID")

args = parser.parse_args()

with open(args.permissions, 'r') as f:
    permissions = json.loads(f.read())

redcap_data = { **permissions, 'username': f"{args.net_id}@washington.edu" }

project = redcap.Project(os.environ['REDCAP_API_URL'], args.project_id)
count = project.update_users([redcap_data])

print(f"Updated permissions for {count} REDCap users.")
