---
version: 1

root:
  # Filtering of messages by level is done at the handler level by using NOTSET
  # on the root logger to emit everything.  This lets us keep console output
  # readable while emitting verbose output to alternate handlers.
  level: NOTSET
  handlers:
    - console
    - syslog

loggers:
  # The SmartyStreets library uses urllib3, which produces DEBUG messages that
  # can contain sensitive data.  Suppress those at its package logger.
  urllib3:
    level: INFO

  # Ditto with various sub-loggers of botocore, which DEBUG out various
  # slightly sensitive things.
  botocore:
    level: INFO

  # But useful to see in logs _where_ credentials were found (env, config, etc)
  botocore.credentials:
    level: DEBUG

  # s3fs sets up a logger with its own console handler, which is bad practice
  # for a library because it subverts the application's (our!) logging config.
  # Set its level to ours.
  s3fs:
    level: !coalesce
      - !LOG_LEVEL
      - INFO

filters:
  unknown sample warnings for controls from id3c etl presence-absence:
    (): id3c.logging.filters.suppress_records_matching
    name: id3c.cli.command.etl.presence_absence
    levelname: WARNING
    msg:
      pattern: Skipping results for sample without a known identifier «(.+?_(Plasmid|PBS|Xeno|Water|HAP1)|NWGC_CONTROL|Water_Control|PTC_.+?)»

  unknown sample warnings for controls from id3c.db.find_identifier:
    (): id3c.logging.filters.suppress_records_matching
    name: id3c.db
    funcName: find_identifier
    levelname: WARNING
    msg:
      pattern: No identifier found for barcode «(.+?_(Plasmid|PBS|Xeno|Water|HAP1)|NWGC_CONTROL|Water_Control|PTC_.+?)»

handlers:
  console:
    class: logging.StreamHandler
    level: !coalesce
      - !LOG_LEVEL
      - INFO
    formatter: console
    filters:
      - unknown sample warnings for controls from id3c etl presence-absence
      - unknown sample warnings for controls from id3c.db.find_identifier

  # This handler emits all log levels; filtering is more usefully done by
  # syslog itself.
  syslog:
    class: id3c.logging.handlers.SysLogUnixSocketHandler
    level: NOTSET
    formatter: syslog

formatters:
  console:
    format: "[%(asctime)s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

  syslog:
    format: "id3c-production[%(process)s] %(name)s %(levelname)s: %(message)s"
