name: shellcheck

on:
  push:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: install
        run: sudo snap install --channel=edge --classic shellcheck

      - name: check
        run: ./dev/shellcheck
